CREATE TABLE STUDENT (
    ROLLNO NUMBER(4) PRIMARY KEY,
    STUDENTNAME VARCHAR2(20) NOT NULL,
    STANDARD VARCHAR2(2) NOT NULL,
    DATE_OF_BIRTH DATE,
    FEES NUMBER(9,2)
);
SELECT * FROM STUDENT;