CREATE OR REPLACE PROCEDURE CAL_NETSAL
(
    P_EMPNO IN NUMBER,
    P_NETSAL OUT NUMBER
)
AS
    V_SAL NUMBER;
    V_COMM NUMBER;
    V_GROSS NUMBER;
    V_IT NUMBER;
BEGIN
    SELECT SALARY, NVL(COMMISSION_PCT,0)
    INTO V_SAL, V_COMM
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = P_EMPNO;

    V_GROSS := V_SAL + V_COMM;

    IF V_COMM = 0 THEN
        V_IT := V_GROSS * 0.10;
    ELSIF V_COMM < 500 THEN
        V_IT := V_GROSS * 0.15;
    ELSE
        V_IT := V_GROSS * 0.20;
    END IF;

    P_NETSAL := V_GROSS - V_IT;
END;
/